# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/refs/heads/main/json-schema/pinact.json
# pinact - https://github.com/suzuki-shunsuke/pinact
version: 3

ignore_actions:
  # These actions don’t have versions
  - name: danielparks/claude-pr-review
    ref: ffaeedbea7afa69130f673fe7f7b4b14e1643732
