exclude: ^deno\.lock$

repos:
  - repo: local
    hooks:
      - id: deno check
        name: deno check
        language: system
        entry: deno check
        files: \.ts$
        pass_filenames: false
        priority: 0
      - id: deno lint
        name: deno lint
        language: system
        entry: deno lint
        files: \.ts$
        pass_filenames: false
        priority: 0
      - id: deno fmt
        name: deno fmt
        language: system
        entry: deno fmt --check
        files: \.(ts|jsonc?)$
        pass_filenames: false
        priority: 0
      - id: deno test
        name: deno test
        language: system
        entry: deno task test
        files: \.ts$
        pass_filenames: false
        priority: 0
      - id: deno run openapi
        name: deno run openapi
        description: Ensure the frontend's copy of openapi.json is up to date.
        language: system
        entry: >-
          sh -c 'deno run -A src/main.ts openapi -o /tmp/repoyear-openapi-check.json
          && diff -u --color=always ../src/api/openapi.json /tmp/repoyear-openapi-check.json'
        files: \.ts$
        pass_filenames: false
        priority: 0
